# Generated by Django 5.0.7 on 2024-10-06 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(help_text='В случае нескольких предприятий одного бренда', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessToUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.CharField(choices=[('owner', 'Owner'), ('mod', 'Moderator'), ('add', 'Add and View'), ('readonly', 'Read Only')], max_length=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='businesses.business')),
            ],
        ),
    ]
