# Generated by Django 5.0.7 on 2024-10-03 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('bonus_salary', models.IntegerField(blank=True, default=0, help_text='Премиальные, надбавка', null=True)),
                ('phone_number', models.CharField(blank=True, help_text="Телефонный номер должен быть в формате '+7(XXX)XXX-XX-XX'", max_length=20, null=True, unique=True)),
                ('telegram_link', models.URLField(blank=True, help_text='Введите телеграмм сотрудника для рассылки уведомлений', null=True)),
                ('date_of_birth', models.DateField()),
                ('business', models.ForeignKey(blank=True, help_text='Выберите бизнес, к которому относится этот сотрудник.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='businesses.business')),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professions.profession')),
            ],
        ),
    ]
