# Generated by Django 5.0.7 on 2024-08-01 08:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('bonus_salary', models.IntegerField(blank=True, default=0, help_text='Премиальные, надбавка', max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть в формате '+7(XXX)XXX-XX-XX', где X - цифра.", regex='^\\+7\\(\\d{3}\\)\\d{3}-\\d{2}-\\d{2}$')])),
                ('telegram_link', models.URLField(blank=True, help_text='Введите телеграмм сотрудника для рассылки уведомлений ', null=True)),
                ('profession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professions.profession')),
            ],
        ),
    ]
