# Generated by Django 5.0.7 on 2024-10-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_business_alter_worker_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='bonus_salary',
            field=models.IntegerField(blank=True, default=0, help_text='Премиальные, надбавка', null=True),
        ),
    ]
