# Generated by Django 5.0.7 on 2024-10-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_alter_worker_bonus_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='last_name',
        ),
        migrations.AddField(
            model_name='worker',
            name='name',
            field=models.CharField(default='имя_обычное', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='telegram_link',
            field=models.URLField(blank=True, help_text='Введите телеграмм сотрудника для рассылки уведомлений', null=True),
        ),
    ]
