# Generated by Django 5.0.7 on 2024-08-01 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_businesstouser_unique_together'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='business',
            field=models.ForeignKey(blank=True, help_text='Выберите бизнес, к которому относится этот сотрудник.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Телефонный номер должен быть в формате '+7(XXX)XXX-XX-XX'", max_length=20, null=True, unique=True),
        ),
    ]
